name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          ls -a
          cd ui2
          ls -a
          docker build -t sports-ui .
          docker save sports-ui:latest -o sports-ui.tar
          chmod 644 sports-ui.tar
          ls -a

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ec2-13-56-197-112.us-west-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH }}
          source: ./ui2/sports-ui.tar
          target: /home/ubuntu/sports-ui.tar

      - name: SSH into EC2 and load Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-56-197-112.us-west-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH }}
          script: |
            sudo docker stop ui-running
            sudo docker rm ui-running
            sudo docker load -i ./sports-ui.tar/ui2/sports-ui.tar
            sudo docker run -d --network host --name ui-running sports-ui:latest
